#!/bin/bash

sudo apt-get update -y

WS_DIR="/home/`whoami`/VPP-WS"

mkdir $WS_DIR

cd $WS_DIR
git clone https://gerrit.fd.io/r/vpp
cd vpp
#git checkout tags/v18.10-rc2 -b v18.10-rc2

cd $WS_DIR
cd vpp
make install-dep
make install-ext-deps build pkg-deb

cd $WS_DIR
cd vpp/build-root
sudo dpkg -i *.deb
